# Mistake

Call [self.error](../%20插件基类/#arkid.core.extension.Extension.error) the method when the API interface needs to return an error

Plug-in developers need to uniformly write their own error. Py files, use enumeration parameters to encapsulate the error codes and messages used by plug-ins at the places where errors need to be returned, call [self.error](../%20插件基类/#arkid.core.extension.Extension.error) the specific enumeration objects that need to be prompted, and this method returns the encapsulated error message dictionary

``` py title="error.py"

from enum import Enum
from arkid.core.translation import gettext_default as _

class ErrorCode(Enum):

    USERNAME_PASSWORD_MISMATCH = ('10001-1', _('username or password not correct', '用户名或密码错误'))
    CONTACT_MANAGER = ('10001-5', _('contact manager', '发生了意外，请联系管理人员'))
    USERNAME_EMPTY = ('10001-6', _('username empty', '用户名为空'))
    ALL_USER_FLAG_LACK_FIELD = ('10001-7', _('fill in at least one user ID', '所有用户标识至少填一个'))
    FIELD_USER_EXISTS = ('10001-8', _('fill in at least one user ID', '{field}字段和已经有的用户重复'))
    PASSWORD_STRENGTH_LACK = ('10001-9', _('password strength lack', ' 密码强度不够'))
    TWO_TIME_PASSWORD_MISMATCH = ('10001-10', _('two time password mismatch', '两次输入的密码不同'))
    OLD_PASSWORD_ERROR = ('10001-10', _('old password error', '旧密码不匹配'))

```

``` py

....
    return self.error(ErrorCode.USERNAME_PASSWORD_MISMATCH)
....
```

If the return value is normal, call [ self.success ](../%20插件基类/#arkid.core.extension.Extension.success) to return

``` py

....
    def api_function(self.request):
        ....
        return self.success({'key':value})
....

```